recipe: default.v1

language: en

pipeline:
- name: WhitespaceTokenizer
  case_sensitive: False
- name: CountVectorsFeaturizer
- name: CountVectorsFeaturizer
  analyzer: "char_wb"
  min_ngram: 1
  max_ngram: 4
- name: LogisticRegressionClassifier
- name: CRFEntityExtractor
- name: EntitySynonymMapper
- name: ResponseSelector
  epochs: 100

policies:
- name: TEDPolicy
  max_history: 10
  epochs: 100
  constrain_similarities: yes
- name: AugmentedMemoizationPolicy
  max_history: 10
- name: RulePolicy
  epochs: 100
  core_fallback_threshold: 0.3
  core_fallback_action_name: "action_default_fallback"
  enable_fallback_prediction: True
assistant_id: 20231202-221250-mode-flour
